version: "3"
services:
  nodeapp:
    image: nodeapp
    container_name: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    networks:
      - backend

networks:
  backend:
    driver: bridge
