global:
  scrape_interval: 30s
  scrape_timeout: 25s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus_service"
    static_configs:
    - targets: ["localhost:9090"]
    
  - job_name: "nodejs_service"
    static_configs:
    - targets: ["localhost:3002"]
